# <p style="padding:20px;background-color:#ffe7a0;margin:0;color:(0,0,0);font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 20px;overflow:hidden;font-weight:900">INTRODUCTION TO NUMPY</p>

# 1. Lí thuyết

## 1.1 NumPy là gì?

**NumPy** (viết tắt của Numerical Python) từ lâu đã là nền tảng của điện toán số (numerical computing) trong Python. Nó cung cấp cấu trúc dữ liệu, thuật toán và thư viện cần thiết cho hầu hết các ứng dụng khoa học liên quan đến dữ liệu số trong Python. Thư viện NumPy bao gồm các đối tượng mảng đa chiều (multidimensional array) và một tập hợp các phương thức để xử lý mảng đa chiều đó. Sử dụng Numpy, các toán tử toán học và logic có thể được thực hiện. Ngoài các khả năng xử lý mảng nhanh mà NumPy có, một trong những ứng dụng chính của Numpy trong phân tích dữ liệu là làm nơi chứa dữ liệu được truyền giữa các thuật toán và thư viện. Đối với dữ liệu số, mảng NumPy hiệu quả hơn để lưu trữ và thao tác dữ liệu so với các cấu trúc dữ liệu Python tích hợp khác. 

**Cài đặt:**  

`pip install numpy`

Sau khi cài đặt hoàn tất, chúng ta cần import nó để sử dụng như các thư viện khác của Python để sử dụng các hàm số của NumPy:

`import numpy as np`

**Ưu điểm:**
-	Chứa bộ các giá trị
-	Có thể chứa các loại dữ liệu khác nhau
-	Có thể thay đổi, thêm, xoá
-	Đầy đủ chức năng tính toán
-	Rất nhiều thư viện được xây dựng sẵn trong NumPy
-	Cần cho Data Science vì thực hiện công việc tính toán trên các bộ dữ liệu với tốc độ cao.

## 1.2 NumPy – Ndarray Object

Đối tượng quan trọng nhất trong Numpy là kiểu mảng N-dimensional được gọi là `ndarray`. Nó mô tả một bộ các item cùng kiểu. Item trong mảng có thể truy xuất bằng cách sử dụng zero-based index.
Mỗi item trong ndarray có cùng kích thước block trong bộ nhớ và là một đối tượng data-type gọi là `dtype`.
Bất kì item nào được trích xuất từ ndarray object bằng cách cắt ra được đại diện bởi một Python object của một kiểu mảng vô hướng (array scalar type).
Một thực thể của ndarray class có thể được tạo ra từ nhiều phương thức tạo mảng khác nhau. Ndarray cơ bản được tạo bằng cách sử dụng phương thức: `numpy.array`.

**Cú pháp:**

`numpy.array(object, dtype=None, copy=True, ndmin=0`

**Trong đó:**
+ **Object**: đối tượng có phương thức giao diện mảng.
+ **Dtype**: loại dữ liệu mong muốn của mảng (tuỳ chọn)
+ **Copy**: mặc định = True đối tượng được copy (tuỳ chọn)
+ **ndmin**: chỉ định kích thước tổi thiểu của mảng kết quả.

## 1.3 Numpy – Data Type

Numpy hỗ trợ rất nhiều kiểu dữ liệu khác nhau như:  
+ **bool** (hay **Boolean**): Đúng hoặc sai, được lưu trữ dưới dạng byte.
+ **int_**: Kiểu số nguyên mặc định (thường là int64 hoặc int32).
+ **int8**: Byte (-128 đến 127).
+ **int16**: Số nguyên (-32768 đến 32767).
+ **int32**: Số nguyên (-2147483648 đến 2147483647).
+ **int64**: Số nguyên (-9223372036854775808 đến 9223372036854775807).
+ **float_**: Viết tắt cho float64.
+ **float16**: bit dấu, số mũ 5 bit, phần định trị 10 bit.
+ **float32**: bit dấu, số mũ 8 bit, phần định trị 23 bit.
+ **float64**: bit dấu, số mũ 11 bit, phần định trị 52 bit.

In [1]:
# install NumPy using popular Python package installer, pip.
# pip install numpy

In [2]:
# Checking NumPy Version
import numpy as np
print(np.__version__)

1.23.5


# 2. Thực hành (Thao tác trên mảng)
## 2.1. Mảng một chiều
+ Từ object có định dạng array, sử dụng: `array()`
+ Từ list, tuple, sử dụng: `asarray()`
+ Có giá trị mặc định là 0, 1, sử dụng: `zeros()` và `ones()`
+ Từ range, sử dụng: `numpy.arange(start, stop, step, dtype)`
+ Từ range có khoảng cách đều nhau, sử dụng: `numpy.linspace(start, stop, num, endpoint, dtype)`
+ Truy xuất phần tử trên mảng theo: `slice(start, stop, step)`
+ Thêm phần tử vào index trong mảng, sử dụng: `insert()`
+ Xoá phần tử tại index trong mảng, sử dụng: `delete()`
+ Broadcasting: thực hiện các phép toán số học trên mảng
+ Statistical function: `max()` hoặc `amax()`, `min()` hoặc `amin()`, `sum()`, `mean()` và `median()`.
+ Sắp xếp trăng dần/giảm dần trong mảng, sử dụng: `sort()`
+ Tìm index của các phần tử trong mảng thoả điều kiện, sử dụng: `where()`
+ Tìm các phần tử trong mảng thoả điều kiện, sử dụng: `extract(điều kiện, mảng)`

### Từ object có định dạng array, sử dụng:   
`array()`

In [3]:
import numpy as np
# Tạo mảng một chiều
array_1 = np.array([1, 2, 3])
print(array_1)

[1 2 3]


In [4]:
# Kiểm tra kiểu data
print(type(array_1))

<class 'numpy.ndarray'>


### Từ list, tuple, sử dụng:   
`asarray()`

In [5]:
# Tạo mảng từ Tuple
x = (1, 2, 3)
b = np.asarray(x)
print(b)

[1 2 3]


### Có giá trị mặc định là 0, 1, sử dụng:   
`zeros()` và `ones()`

In [6]:
# Mảng với các phần tử có giá trị ban đầu là 0
mang_0 = np.zeros((5, ), dtype = int)
print(mang_0)

[0 0 0 0 0]


In [7]:
# Mảng với các phần tử có giá trị ban đầu là 1
mang_1 = np.ones(5)
print(mang_1)

[1. 1. 1. 1. 1.]


### Từ range, sử dụng:  
`numpy.arange(start, stop, step, dtype)`

In [8]:
mang_2 = np.arange(10, 20, 2)
print(mang_2)

[10 12 14 16 18]


### Từ range có khoảng cách đều nhau, sử dụng:  
`numpy.linspace(start, stop, num, endpoint, dtype)`

In [9]:
mang_3 = np.linspace(10, 20, 5)
print('Kết quả mang_3 là:',mang_3)

mang_4 = np.linspace(10, 20, 5, endpoint=False)
print('Kết quả mang_4 là:', mang_4)

Kết quả mang_3 là: [10.  12.5 15.  17.5 20. ]
Kết quả mang_4 là: [10. 12. 14. 16. 18.]


=> Trong đó: lấy giá trị cuối thì `endpoint=True`, ngược lại, không lấy thì `endpoint=False`

### Truy xuất phần tử trên mảng theo index (từ 0 đến chiều dài mảng -1)

In [10]:
# Truy xuất phần tử trong mảng
mang_5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # index bắt đầu từ 0
print(mang_5)
print(mang_5[5]) # lấy index 5
print(mang_5[3:]) # từ index 3, lấy hết
print(mang_5[3:5]) # từ index 3 lấy đến index 4
print(mang_5[mang_5 < 5]) # có kèm điều kiện

[ 1  2  3  4  5  6  7  8  9 10]
6
[ 4  5  6  7  8  9 10]
[4 5]
[1 2 3 4]


### Truy xuất phần tử trên mảng theo:   
`slice(start, stop, step)`

In [11]:
# Truy xuất các phần tử trong mảng dùng slice
mang_5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
s = slice(3, 8, 2)
print(mang_5[s])
print(mang_5[s][1])

[4 6 8]
6


### Thêm các phần tử vào cuối mảng, sử dụng:   
`append()`

In [12]:
# Thêm các phần tử vào cuối mảng
mang_5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mang_5 = np.append(mang_5, [24, 27])
print(mang_5)

[ 1  2  3  4  5  6  7  8  9 10 24 27]


### Thêm phần tử vào index trong mảng, sử dụng:  
`insert()`

In [13]:
# Thêm phần tử vào index = 3, giá trị 100
print(mang_5)
mang_5 = np.insert(mang_5, 3, 100)
print(mang_5)

[ 1  2  3  4  5  6  7  8  9 10 24 27]
[  1   2   3 100   4   5   6   7   8   9  10  24  27]


### Xoá phần tử tại index trong mảng, sử dụng:   
`delete()`

In [14]:
# Xoá phần tử tại vị trí index = 8
print(mang_5)
mang_5 = np.delete(mang_5, 8)
print(mang_5)

[  1   2   3 100   4   5   6   7   8   9  10  24  27]
[  1   2   3 100   4   5   6   7   9  10  24  27]


### Broadcasting: thực hiện các phép toán số học trên mảng

In [15]:
m = np.array([1, 2, 3, 4])
n = np.array([5, 6, 7, 8])

mang_cong = m + n
print("Mang cong la:", mang_cong)

mang_tru = m - n
print("Mang tru la:", mang_tru)

mang_nhan = m*n
print("Mang_nhan:", mang_nhan)

mang_chia = m/n
print("Mang chia la:", mang_chia)

Mang cong la: [ 6  8 10 12]
Mang tru la: [-4 -4 -4 -4]
Mang_nhan: [ 5 12 21 32]
Mang chia la: [0.2        0.33333333 0.42857143 0.5       ]


### Statistical function

In [16]:
d = np.array([3, 6, 4, 8, 10, 6, 3])

# Tìm max dùng max() or amax()
print(np.max(d))
print(np.amax(d))

# Tìm min dùng min() or amin()
print(np.amin(d))
print(np.amin(d))

10
10
3
3


In [17]:
# Tính tổng giá trị, sử dụng sum()
d = np.array([3, 6, 4, 8, 10, 6, 3])
d.sum()

40

In [18]:
# Giá trị trung bình số học, sử dụng: mean()
d = np.array([3, 6, 4, 8, 10, 6, 3])
print(np.mean(d))

5.714285714285714


In [19]:
# Giá trị trung bình giữa, median() dựa trên mảng đã sắp xếp tăng dần, lấy trung bình phần tử ở giữa mảng
e = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.median(e))

4.5


### Sắp xếp trăng dần/giảm dần trong mảng, sử dụng:  
`sort()`

In [20]:
d = np.array([3, 6, 4, 8, 10, 6, 3])
print("Sắp xếp tăng dần:", np.sort(d))
print("Sắp xếp giảm dần:", np.sort(d)[::-1])

Sắp xếp tăng dần: [ 3  3  4  6  6  8 10]
Sắp xếp giảm dần: [10  8  6  6  4  3  3]


### Tìm index của các phần tử trong mảng thoả điều kiện, sử dụng:  
`where()`

In [21]:
print(d)
indexes = np.where(d >= 5)
print(indexes)
print(d[indexes])

[ 3  6  4  8 10  6  3]
(array([1, 3, 4, 5]),)
[ 6  8 10  6]


### Tìm các phần tử trong mảng thoả điều kiện, sử dụng:  
`extract(điều kiện, mảng)`

In [22]:
print(d)
print(np.extract(np.mod(d, 2) == 0, d))
print(np.extract(d >= 5, d))

[ 3  6  4  8 10  6  3]
[ 6  4  8 10  6]
[ 6  8 10  6]


## 2.2 Mảng nhiều chiều
### Tương tự như mảng một chiều

In [23]:
# Tạo mảng 
array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2)
print(type(array_2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [24]:
# Tạo mảng với 0 hoặc 1
mang_zeros = np.zeros([2, 2, 2], dtype=int)
print("Mang 0:", mang_zeros)

mang_ones = np.ones([2, 2], dtype=int)
print("Mang 1:", mang_ones)

Mang 0: [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
Mang 1: [[1 1]
 [1 1]]


In [25]:
# Số dòng, số cột trên mảng
print(array_2.shape)

(2, 3)


In [26]:
# Cập nhật phần tử trong mảng
array_2[0][0] = 100
print(array_2)

[[100   2   3]
 [  4   5   6]]


In [27]:
# Truy xuất phần tử trong mảng
print(array_2)
print(array_2[1, 2])
print(array_2[1, ])

[[100   2   3]
 [  4   5   6]]
6
[4 5 6]


In [28]:
# Thay đổi kích cỡ mảng
print(array_2)
print(array_2.shape)
array_2.shape = (3, 2)
print(array_2)

[[100   2   3]
 [  4   5   6]]
(2, 3)
[[100   2]
 [  3   4]
 [  5   6]]


In [29]:
# Thay đổi kích cỡ mảng dùng reshape
a = np.arange(24)
print(a)
b = a.reshape(2, 3, 4) # Ma traajn, dòng, cột
print(b)
print(b[0][1][2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
6


### Thực hiện các phép toán số học trên mảng
+ Tìm `max()`, `min()` (hoặc dùng `amax()` và `amin()`)
+ Trung bình: `mean()`
+ Trung bình giữa (trung vị): `median()`
+ Độ lệch chuẩn: `std()`
+ Hệ số tương quan (Peason Product)

In [30]:
# Tính toán độ lệch chuẩn standard deviation
a = np.array([[1, 2], [3, 4]])
print(a)
print(np.std(a))
print(np.std(a, axis = 0)) # 0: cột (tính trên cột)
print(np.std(a, axis = 1)) # 1: dòng

[[1 2]
 [3 4]]
1.118033988749895
[1. 1.]
[0.5 0.5]


In [31]:
# Tính toán hệ số tương quan theo thời điểm (Peason Product)
b = np.array([[1, 4, 6], [1, 2, 3]])
print(a)
print("Coefficient")
print(np.corrcoef(a[0], a[1]))

[[1 2]
 [3 4]]
Coefficient
[[1. 1.]
 [1. 1.]]


**<span style="color:#034235;"> Thanks for reading this post. </span>**
_______
_Make by_**<span style="color:#034235;"> Lucas,</span>**
### <p style="padding:5px;background-color:#034235;margin:0;color:#ffe7a0;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 20px;overflow:hidden;font-weight:900">END</p>
______
<img src="https://github.com/LeHongNgoc3820/Lucas_viet_Blog/blob/b5e2de5a812292889e793b719572d06f3ababf2d/Logo%20ta%CC%81ch%20ne%CC%82%CC%80n.png?raw=true"
     style="width:200px;height:200px;">

**<span style="color:#034235;"> You can contact with me on:</span>**
+ **Gmail**: lehongngoc.work@gmail.com
+ **GitHub**: [LeHongNgoc3820](https://github.com/LeHongNgoc3820)
+ **Linkedln**: [Ngoc Le Hong](https://www.linkedin.com/in/ngoc-le-hong-44131b21a/)